import Link from "next/link";
import { ArrowLeft, Book, Code, Terminal, Zap } from "lucide-react";

export default function DocsPage() {
  return (
    <main className="min-h-screen bg-zinc-950 text-zinc-300 font-sans p-8 flex flex-col items-center">
      <div className="w-full max-w-4xl flex flex-col gap-8">
        <header className="flex items-center gap-4 border-b border-white/5 pb-6">
          <Link href="/" className="h-8 w-8 rounded-lg bg-white/5 flex items-center justify-center text-zinc-400 hover:text-white transition-colors">
            <ArrowLeft size={16} />
          </Link>
          <div>
            <h1 className="text-2xl font-bold text-white flex items-center gap-2">
              <Book size={20} className="text-cyan-400" /> Documentation
            </h1>
            <p className="text-xs text-zinc-500 mt-1">DeployPilotOS SRE Core Documentation & API Reference</p>
          </div>
        </header>

        <section className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {[
            { icon: <Terminal size={18} className="text-emerald-400" />, title: "Quickstart Guide", desc: "Get DeployPilotOS running locally in under 3 minutes.", href: "/docs/quickstart" },
            { icon: <Code size={18} className="text-blue-400" />, title: "API Reference", desc: "Integrate with our REST API to push external monitoring metrics.", href: "/docs/api" },
            { icon: <Zap size={18} className="text-yellow-400" />, title: "Runbook Triggers", desc: "Learn how to write custom automated playbooks.", href: "/docs/runbooks" },
            { icon: <Book size={18} className="text-purple-400" />, title: "Architecture", desc: "Deep dive into the underlying multi-agent simulation framework.", href: "/docs/architecture" }
          ].map((card, i) => (
            <Link href={card.href} key={i} className="bg-zinc-900/30 border border-white/5 p-6 rounded-xl hover:bg-white/5 hover:border-white/10 transition-all cursor-pointer group block">
              <div className="flex items-center gap-3 mb-3">
                <div className="h-10 w-10 rounded-lg bg-zinc-950 border border-white/5 flex items-center justify-center group-hover:scale-110 transition-transform">
                  {card.icon}
                </div>
                <h3 className="text-sm font-semibold text-white">{card.title}</h3>
              </div>
              <p className="text-xs text-zinc-400 leading-relaxed">{card.desc}</p>
            </Link>
          ))}
        </section>

        <div className="bg-gradient-to-r from-cyan-500/10 to-transparent border border-cyan-500/20 p-6 rounded-xl">
          <h2 className="text-sm font-bold text-white mb-2">Notice</h2>
          <p className="text-xs text-zinc-400">
            DeployPilotOS is currently in Early Access. Full documentation is being generated by the core engineering team and will be released in the upcoming stable build.
          </p>
        </div>
      </div>
    </main>
  );
}
