"use client";
import { useRef, useState } from "react";
import { Activity, AlertTriangle, CheckCircle2, Server, ShieldCheck, Zap } from "lucide-react";
import type { Diagnosis } from "@/src/lib/openai/diagnose";

const steps = ["Anomaly detected: latency crossed the 500ms threshold (847ms).", "Fetching logs and deployment history…", "Found pool timeouts beginning 21 seconds after v2.4.1.", "Deploy v2.4.1 changed pool_size from 25 to 10.", "Root cause identified with 94% confidence.", "Restoring pool_size and restarting connection manager…", "Health check passed: 38ms latency, 0.001% errors."];

export function DemoConsole() {
  const [feed, setFeed] = useState<string[]>(["Monitoring api-service. Rolling baseline is stable."]);
  const [running, setRunning] = useState(false); const [resolved, setResolved] = useState(false); const [diagnosis, setDiagnosis] = useState<Diagnosis | null>(null);
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const simulate = async () => {
    if (running) return; if (timer.current) clearTimeout(timer.current);
    setRunning(true); setResolved(false); setDiagnosis(null); setFeed(["P1 incident opened — API Timeout Cascade"]);
    let index = 0; const tick = () => { const next = steps[index++]; if (!next) { setRunning(false); setResolved(true); return; } setFeed(current => [...current, next]); timer.current = setTimeout(tick, 700); }; timer.current = setTimeout(tick, 450);
    const result = await fetch("/api/diagnose", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ service: "api-service" }) }); if (result.ok) setDiagnosis(await result.json());
  };
  return <main className="console"><header className="topbar"><div className="brand"><span className="brand-mark">✦</span> DeployPilotOS <small>MISSION CONTROL</small></div><div className="agent-state"><i className={running ? "red" : ""}/>{running ? "1 ACTIVE INCIDENT" : "AGENT STATUS: ALL SYSTEMS GO"}</div></header><div className="app-shell"><aside className="sidebar"><p className="section-label">SERVICES</p>{["api-service","web-frontend","database-primary","worker-service"].map((s,i)=><button className="service" key={s}><i className={i===0&&running ? "red" : i===2 ? "yellow" : ""}/><span>{s}<small>{i===0&&running ? "INCIDENT" : "Healthy"}</small></span></button>)}</aside><section className="workspace"><div className="dashboard-head"><div><p className="eyebrow">LIVE OPERATIONS</p><h2>Good evening, Harish ✦</h2><p>Your infrastructure is being watched.</p></div><button className="button primary simulate" onClick={simulate}><Zap size={16}/>{running ? "Investigating…" : "Simulate incident"}</button></div>{(running||resolved)&&<section className={resolved ? "incident-banner resolved" : "incident-banner"}>{resolved ? <CheckCircle2/> : <AlertTriangle/>}<div><p>{resolved ? "INCIDENT AUTO-RESOLVED" : "P1 CRITICAL INCIDENT"}</p><h3>API Timeout Cascade — DB Connection Pool Exhausted</h3><span>{resolved ? "Resolved in 9 seconds · Health checks verified" : "Investigation in progress"}</span></div></section>}<section className="stats"><Stat icon={<Server/>} value="4" label="Total services"/><Stat icon={<AlertTriangle/>} value={running ? "1" : "2"} label="Incidents today"/><Stat icon={<Activity/>} value="3m 42s" label="Average MTTR"/><Stat icon={<ShieldCheck/>} value="99.97%" label="Uptime SLA"/></section><section className="grid-main"><div className="card health-card"><h3>Service health timeline</h3><div className="chart"><svg viewBox="0 0 600 180" preserveAspectRatio="none"><path d="M0 150 L100 132 200 123 300 110 400 96 480 104 520 30 550 130 600 118" fill="none" stroke="#4ade80" strokeWidth="3"/><circle cx="520" cy="30" r="6" fill="#f87171"/></svg></div></div><div className="card activity-card"><h3>Agent activity · Live</h3><div className="activity-list">{feed.map((item,i)=><div className="activity" key={`${i}-${item}`}><i className={i===feed.length-1&&running ? "active" : ""}/><div><small>23:47:{String(i+2).padStart(2,"0")}</small><p>{item}</p></div></div>)}</div></div></section>{diagnosis&&<section className="card diagnosis"><div><p className="eyebrow">AI DIAGNOSIS · {diagnosis.confidence}% CONFIDENCE</p><h3>{diagnosis.rootCause}</h3></div><ul>{diagnosis.evidence.map(e=><li key={e}>{e}</li>)}</ul></section>}</section></div></main>;
}
function Stat({icon,value,label}:{icon:React.ReactNode;value:string;label:string}) { return <div className="card stat"><div className="stat-icon">{icon}</div><div><strong>{value}</strong><p>{label}</p></div></div>; }
